version: '3'

volumes:
  my_awesome_project_local_postgres_data: {}
  my_awesome_project_local_postgres_data_backups: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: my_awesome_project_local_django
    container_name: my_awesome_project_local_django
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - '8000:8000'
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: my_awesome_project_production_postgres
    container_name: my_awesome_project_local_postgres
    volumes:
      - my_awesome_project_local_postgres_data:/var/lib/postgresql/data
      - my_awesome_project_local_postgres_data_backups:/backups
    env_file:
      - ./.envs/.local/.postgres
    ports:
      - 5432:5432

  pg-admin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=dakaraefe@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=admin
      - PGADMIN_LISTEN_PORT=5050

    ports:
      - "5050:5050"

  redis:
    image: redis:6
    container_name: my_awesome_project_local_redis

  celeryworker:
    <<: *django
    image: my_awesome_project_local_celeryworker
    container_name: my_awesome_project_local_celeryworker
    depends_on:
      - redis
      - postgres
    ports: []
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: my_awesome_project_local_celerybeat
    container_name: my_awesome_project_local_celerybeat
    depends_on:
      - redis
      - postgres
    ports: []
    command: /start-celerybeat

  flower:
    <<: *django
    image: my_awesome_project_local_flower
    container_name: my_awesome_project_local_flower
    ports:
      - '5555:5555'
    command: /start-flower
